### ISSUE TITLE
No dark mode

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-run-hello#14]
Let's respect developers' eyes and add a dark variant of the congrats webpage.

Sprinkle some `@media (prefers-color-scheme: dark)`

**Comment by steren** [comment]
Cc @code128 @chemichelle ;)

**Comment by chemichelle** [comment]
Screenshot of the dark mode version: https://screenshot.googleplex.com/FHcYURJdUSH :)

**Comment by steren** [comment]
Note: you should directly paste the screenshot here. The URL you linked to is google internal.

**Comment by steren** [comment]
I love the background!

**Comment by steren** [comment]
Dark mode was added in https://github.com/GoogleCloudPlatform/cloud-run-hello/commit/e5f1bcfb4b2376dea2001fccf043145a9dc9ae8f

**Comment by steren** [comment]
I do not know. And this question is out of scope of this repo
