### ISSUE TITLE
Add automated testing

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/cloud-run-hello#23]
In porting this sample for [other uses](https://github.com/GoogleCloudPlatform/cloud-code-samples/pull/217), I implemented a CI/CD pipeline using Cloud Build. Not sure if I can setup the trigger here but happy to relay the necessary configuration and test code here.

**Comment by steren** [comment]
This repo is automatically built with Cloud Build and deployed to gcr.io/cloudrun/hello.

Any build failure would be enough to not push the container.

I am not really sure what else we can add as test. A test that verifies the page prints appropriate info?
