### ISSUE TITLE
Panic right after pushing image

### ISSUE THREAD

**Issue by chew-z** [GoogleCloudPlatform/cloud-run-hello#6]
Something terrible is happening. After building and pushing image I get panic as below.

I can make new revision from pushed image in Cloud Run Console and everything works OK.

```
[ ✓ ] Pushed container image to Google Container Registry.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x87b8af]

goroutine 1 [running]:
main.optionsToFlags(...)
        /src/cmd/cloudshell_open/cloudrun.go:37
main.run(0x7ffd00e04221, 0x2d, 0x0, 0x0, 0x0, 0x0, 0xa6e1e0, 0xc000198710)
        /src/cmd/cloudshell_open/main.go:300 +0x198f
main.main()
        /src/cmd/cloudshell_open/main.go:81 +0x207r ``

BTW: I find this error a happy coincidence as it stops and lets me play with Docker image before publishing new revision.

**Comment by ahmetb** [comment]
This is being fixed in cloud-run-button repo. 
cc: @jamesward 
Thanks for reporting.

**Comment by jamesward** [comment]
Yeah, I screwed this up.  :(
Watch here for updates: https://github.com/GoogleCloudPlatform/cloud-run-button/issues/128

**Comment by chew-z** [comment]
No problem ;-) that's part of this trade.

But it is actually a great feature stopping after pushing image on completely virgin temporary Google Cloud Shell.  Perhaps you consider adding this as an option?
