### ISSUE TITLE
Main CTA is below the fold

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-run-hello#9]
With the new design, the main call to action (take the quickstart) is now below the fold and not very visible on a standard screen.

See 
![image](https://user-images.githubusercontent.com/360895/73237901-ee06d800-414b-11ea-9154-702a114aaa8a.png)

CC @code128 @chemichelle

**Comment by code128** [comment]
What screen size are you viewing this at? We'll create a pull request that addresses #9,11,12
