### ISSUE TITLE
The $PORT in the log message is a literal

### ISSUE THREAD

**Issue by ferrarimarco** [GoogleCloudPlatform/cloud-run-hello#90]
Hi folks!

When deploying this service on Cloud Run, the `$PORT` is printed as a literal in the log:

```
2024/04/17 14:13:36 Hello from Cloud Run! The container started successfully and is listening for HTTP requests on $PORT
```

Shall this be formatted?

https://github.com/GoogleCloudPlatform/cloud-run-hello/blob/7e45d10641efba44275ceed0c0aff2cc60a2866c/hello.go#L188

Thanks for your support!

**Comment by JulienBreux** [comment]
Hi @ferrarimarco,

Thanks for contributing.

Fix in progress.

Have a nice day :)

**Comment by ferrarimarco** [comment]
Thanks @JulienBreux !
